% Personajes de Avengers 1 y Avengers 2
personaje(iron_man).
personaje(captain_america).
personaje(thor).
personaje(hulk).
personaje(black_widow).
personaje(hawkeye).
personaje(nick_fury).
personaje(maria_hill).
personaje(phil_coulson).
personaje(erik_selvig).
personaje(pepper_potts).
personaje(jasper_sitwell).
personaje(loki).
personaje(chitauri).
personaje(thanos).
personaje(ultron).
personaje(baron_strucker).
personaje(ulysses_klaue).
personaje(dr_list).
personaje(war_machine).
personaje(falcon).
personaje(wanda_maximoff).
personaje(pietro_maximoff).
personaje(vision).
personaje(helen_cho).
personaje(cameron_klein).
personaje(laura_barton).
personaje(cooper_barton).
personaje(lila_barton).
personaje(nathaniel_barton).
personaje(heimdall).
personaje(peggy_carter).
personaje(jarvis).
personaje(friday).
personaje(costel).
